/**
 * THE FIRM'S EIGHT NOTICES, AND WHETHER THEY ARE STILL FIT TO SEND.
 *
 * A section 129 and a letter of demand on day 1, a final notice on day 12, a listing notice on
 * day 39 and an intended-summons notice on day 49 — each written twice, for a person and for a
 * company. They are generated by scripts/letters/ from the firm's own typeset specimens.
 *
 * WHAT THIS GUARDS, and every one of these is silent:
 *
 *   - A MERGE FIELD THAT DOES NOT EXIST. `renderTemplate` leaves an unresolved placeholder
 *     STANDING rather than blanking it, which is the right behaviour and means a misspelt field
 *     reaches a debtor as "{{balance}}" in the middle of a statutory demand.
 *   - A FIELD OUTSIDE THE COLLECTIONS SCOPE. The firm's business account is not on the
 *     collections list, and a notice that asked a debtor to pay commission into it would be trust
 *     money in the wrong place, found at month end.
 *   - A CHARACTER THE PDF CANNOT DRAW. Charter is subsetted to Windows-1252; a euro or an arrow
 *     pasted in from somewhere refuses the whole attachment at the moment somebody tries to send.
 *   - THE PARSE NOT BEING TOTAL. Every block has to be one the renderer knows, or the notice is
 *     drawn correctly, saved as fewer blocks than it had, and shorter for ever afterwards.
 *
 * Run: node --import ./scripts/qa/tsresolve.mjs scripts/qa/check-letters.mjs
 */
import { readFileSync } from 'node:fs'
import { A4_LETTERHEAD, canUseLetter, letterProblems } from '../../src/lib/letterDocument.ts'
import { MERGE_FIELDS, renderTemplate, sampleValues } from '../../src/lib/messageTemplates.ts'
import { planLetter } from '../../src/lib/letterLayout.ts'
import { printableForPdf } from '../../src/lib/winAnsi.ts'
import { CHARTER_GAPS } from '../../src/lib/charter.ts'

let pass = 0
const failures = []
function check(name, actual, expected) {
  const a = JSON.stringify(actual)
  const b = JSON.stringify(expected)
  if (a === b) { pass += 1; return }
  failures.push(`${name}\n    expected ${b}\n    got      ${a}`)
}
const ok = (name, actual) => check(name, actual, true)

const letters = JSON.parse(readFileSync('scripts/letters/letters.json', 'utf8'))
const values = sampleValues()
const KNOWN = new Set(MERGE_FIELDS.collections.map((f) => f.key))

/* THE EIGHT THE WORKFLOW NEEDS, named rather than counted: a check that only counted would pass
   with two copies of one letter and the demand missing. */
const WANTED = [
  'letter-s129-individual', 'letter-demand-company',
  'letter-final-notice-individual', 'letter-final-notice-company',
  'letter-listing-individual', 'letter-listing-company',
  'letter-summons-individual', 'letter-summons-company',
]
check('the eight notices the workflow attaches are all there',
  Object.keys(letters).sort(), [...WANTED].sort())

/** Every span of a document, wherever it is nested. The parse must be total, so this must be. */
function spansOf(doc) {
  const out = []
  const eat = (spans) => { for (const s of spans ?? []) out.push(s) }
  for (const b of doc.blocks) {
    if (b.kind === 'table') { for (const row of b.rows) for (const c of row) eat(c.spans) }
    else if (b.kind === 'list') { for (const item of b.items) eat(item) }
    else eat(b.spans)
  }
  return out
}

const KINDS = new Set(['heading', 'paragraph', 'list', 'table', 'spacer', 'signature', 'pagebreak'])

for (const key of WANTED) {
  const doc = letters[key]
  const who = key.endsWith('-company') ? 'company' : 'individual'

  ok(`${key}: is a letter document`, doc?.defaults !== undefined && Array.isArray(doc?.blocks))
  ok(`${key}: every block is one the renderer knows`,
    doc.blocks.every((b) => KINDS.has(b.kind)))

  /* The firm asked for Charter off their own section 129, so that is what these are set in. */
  ok(`${key}: is set in Charter`, /charter/i.test(doc.defaults.font))

  /*
   * EVERY FIELD IT ASKS FOR EXISTS, AND IS ON THE COLLECTIONS SIDE. The business account is
   * deliberately not on that list: a notice asking a debtor to pay commission into it would be
   * trust money in the wrong place, and nobody would find out until month end.
   */
  const text = spansOf(doc).map((s) => s.text).join(' ')
  const asked = [...new Set([...text.matchAll(/\{\{([a-z_]+)\}\}/g)].map((m) => m[1]))]
  const unknown = asked.filter((f) => !KNOWN.has(f))
  check(`${key}: asks for no field the collections side does not have`, unknown, [])

  /* AND THE RIGHT HALF OF THE PAIR. A person has an identity number and a company a registration
     number; the wrong one on a notice is a field that resolves to nothing for that debtor. */
  if (who === 'individual') {
    ok(`${key}: identifies the debtor by identity number`, asked.includes('debtor_id_masked'))
    ok(`${key}: ...and never by a registration number`, !asked.includes('debtor_reg_no'))
  } else {
    ok(`${key}: identifies the company by registration number`, asked.includes('debtor_reg_no'))
    ok(`${key}: ...and never by an identity number`, !asked.includes('debtor_id_masked'))
  }

  /* THE CASE NUMBER, NOT THE CLIENT'S REFERENCE. The firm's decision, and the reason for it is
     that theirs is used on more than one account 5,013 times over. */
  ok(`${key}: leads with our own case number`, asked.includes('case_number'))

  /* FIT TO SEND: letterProblems is what the composer asks before it will attach one. */
  const problems = letterProblems(doc, 'collections')
  ok(`${key}: is fit to send`, canUseLetter(problems))

  /*
   * AND IT DRAWS. Every character through the same repertoire the PDF has -- Charter is subsetted
   * to Windows-1252 and a euro or an arrow refuses the whole attachment at the moment somebody
   * tries to send it, which is the worst possible moment to find out.
   */
  const merged = renderTemplate(text, values)
  /*
   * ASKED LINE BY LINE, because a newline inside a span is CONTENT and not a fault. The signature
   * block is four lines in one span, and the layout splits on them before anything is drawn --
   * printableForPdf reports a newline as unprintable precisely because one arriving AT THE DRAW
   * means the layout failed. Run over the whole concatenation it reported every one of the eight
   * letters as undrawable, which the real PDFs plainly are not.
   */
  const bad = [...new Set(merged.text.split('\n')
    .flatMap((line) => printableForPdf(line, CHARTER_GAPS).unprintable))]
  check(`${key}: contains nothing the PDF cannot draw`, bad, [])
  check(`${key}: every field resolves against the library's own samples`, merged.missing, [])

  /* AND IT PAGINATES. A notice that throws while being laid out is one that cannot be attached. */
  const plan = planLetter(doc, A4_LETTERHEAD,
    { measure: (t, s) => t.length * s * 0.19, filled: true, values })
  ok(`${key}: lays out onto pages (${plan.pages.length})`, plan.pages.length >= 1)
  /* Nothing in this set is a ten-page document; one that suddenly is has a table that stopped
     wrapping, which is visible on paper and nowhere else. */
  ok(`${key}: ...and is not longer than a notice should be`, plan.pages.length <= 6)
}

/*
 * THE TRUST ACCOUNT IS WRITTEN ONE WAY. All eight name the firm's bank details, and the whole
 * argument for bankLine is that the same account written two ways across two notices reads as two
 * accounts. Here that means every letter asks for the same four fields.
 */
const bankFields = WANTED.map((key) => {
  const text = spansOf(letters[key]).map((s) => s.text).join(' ')
  return [...new Set([...text.matchAll(/\{\{(firm_bank[a-z_]*)\}\}/g)].map((m) => m[1]))].sort().join(',')
})
check('every notice names the trust account the same way', [...new Set(bankFields)].length, 1)
ok('...and it is the TRUST account, never the business one',
  !bankFields[0].includes('business'))

/*
 * WHICH EMAIL POSTS WHICH NOTICE.
 *
 * Ten of the firm's fourteen collections emails carry a PDF; the other four are the two handover
 * messages and the two that warn a listing is being prepared, and they say so in their own words
 * rather than attaching anything. The pairing itself is set on `message_templates.attachment_id`
 * in the database, where the composer reads it -- but the database is not a record anybody can
 * review, and a second environment starts with none of it. attachments.json is that record, and
 * it is what the wiring was applied from.
 *
 * WHAT IT GUARDS is the one mistake with a real cost: an email written to a person that posts the
 * notice written for a company. Both exist for every step, their names differ by one word, and
 * the company notice tells its reader their company may be wound up and its directors held
 * personally liable. Sent to a pensioner it is not a typo.
 *
 * Read the other way, it also catches a notice nothing posts. A letter in the library that no
 * email attaches is one the workflow will never send, which looks like a working library right up
 * until the step that was supposed to carry it goes out bare.
 */
const attaches = JSON.parse(readFileSync('scripts/letters/attachments.json', 'utf8'))
const wanted = new Set(WANTED)

for (const [email, letter] of Object.entries(attaches)) {
  ok(`${email}: posts a notice the firm has written`, wanted.has(letter))
  /* The suffix is the audience on both sides -- it is how the library names the pair, and how a
     collector tells them apart in the picker. */
  const emailFor = email.endsWith('-company') ? 'company' : 'individual'
  const letterFor = letter.endsWith('-company') ? 'company' : 'individual'
  check(`${email}: ...written for the same debtor it is addressed to`, letterFor, emailFor)
}

const posted = new Set(Object.values(attaches))
check('every notice is posted by at least one email',
  WANTED.filter((k) => !posted.has(k)), [])

/* ------------------------------------------------------------------ */

for (const f of failures) console.error(`  ✗ ${f}`)
console.log(`check-letters: ${pass} passed, ${failures.length} failed`)
process.exit(failures.length ? 1 : 0)
